### ISSUE TITLE
What do you think about krausest/js-framework-benchmark?

### ISSUE THREAD

**Issue by aclueless** [schell/todo-mvc-bench#35]
The benchmark repo is here: https://github.com/krausest/js-framework-benchmark (JFB)

I found that JFB host source codes (implementations) and anyone who want to run the bench have to build them. Rust's frameworks are the exceptions because most frameworks are in JS and users are not expected having Rust on their system.

On the other hand, this bench mark does not host implementation but binaries. And I saw that you also have your Rust's framework (mogwai). Does your target audience/users are crustaceans? How about hosting the implementation/source code instead of binaries?

If you choose to host the source code, I think that the benchmark-app may have a feature that loads and displays implementations (for comparison on source code other than just comparing performance only)

**Comment by schell** [comment]
> What do you think about krausest/js-framework-benchmark?

That benchmark looks promising. Without giving it a deep dive I wouldn't know how sound it is.

> Does your target audience/users are crustaceans? 

Mogwai's audience are Rust developers, but I've thought about writing JS bindings and publishing an NPM package. It's not on my current roadmap though.

> How about hosting the implementation/source code instead of binaries?

I prefer to host the binaries/compiled payloads. Mostly because I don't want the requirement of managing a javascript toolchain. It is fairly easy to add a new framework (or multiple versions of one framework) to this benchmark though, and I can add a link to the source for each which in my opinion would fulfill displaying comparisons of source code.

**Comment by schell** [comment]
Thanks for your interest! :clinking_glasses:

**Comment by aclueless** [comment]
> Mogwai's audience are Rust developers

Oh, sorry for the confusion. The question is about this repo: **todo-mvc-bench**.

**Comment by aclueless** [comment]
I mean that "*Does todo-mvc-bench focus on benchmarking mainly Rust frameworks?*" Only few JS frameworks included for some insight about how Rust perform vs JS.

**Comment by schell** [comment]
todo-mvc-bench is meant to be a general comparison of web frameworks in different languages. So far I only have Javascript, Rust, Elm, Closure and Haskell, with the majority of frameworks being in Javascript or Rust. The purpose of the benchmark is to help me optimize mogwai.

**Comment by aclueless** [comment]
> I prefer to host the binaries/compiled payloads
> general comparison of web frameworks in different languages

Yeah, I understand why you want binaries/compiled instead of source code now!
